don't look for /etc/resolv.conf on windows
rancher-sandbox/rancher-desktop-host-resolver pull request #15
Opened 2022-05-04 16:50 UTC by Nino-K

This could be misleading when the host process looks for `/etc/resolv.conf` on the windows and emits a log line that can be misleading. Also, we should set the fallback IPs if the upstream assignment fails. 

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-05-04 23:18 UTC, mook-as requested changes
Checked with `godbolt.org` — the default compiler does optimize out code based on `runtime.GOOS`.

2022-05-04 23:18 UTC, mook-as commented on pkg/dns/dns.go
>  			cc, err = newStaticClientConfig(defaultFallbackIPs)
Should probably add a comment saying that on Windows, we only ever use hard-coded servers for fallback.

2022-05-04 23:18 UTC, mook-as commented on pkg/dns/dns.go
>  		}
(Optional) Maybe do it like
```go
if cc, err = … ; err != nil {
  if cc, err = … ; err != nil {
    return nil, err
```

2022-05-16 22:39 UTC, mook-as approved these changes

2022-05-16 22:39 UTC, mook-as commented on pkg/dns/dns.go
> +			if cc, err = newStaticClientConfig(defaultFallbackIPs); err != nil{
Nit: space before brace.

2022-05-16 23:03 UTC, Nino-K commented on pkg/dns/dns.go
> +			if cc, err = newStaticClientConfig(defaultFallbackIPs); err != nil{
How did that pass the linter 🤔

2022-05-17 19:01 UTC, mook-as commented on pkg/dns/dns.go
> +			if cc, err = newStaticClientConfig(defaultFallbackIPs); err != nil{
https://github.com/rancher-sandbox/rancher-desktop-host-resolver/blob/325fb3dc92af0804f94c8e2c0da3d5e6f195ba21/.golangci.yml#L1-L3

2022-05-17 21:21 UTC, mook-as approved these changes

2022-05-17 21:21 UTC, merged