Remove lima DNS fork
rancher-sandbox/rancher-desktop-host-resolver pull request #27
Opened 2022-07-13 00:50 UTC by Nino-K

Related to https://github.com/rancher-sandbox/rancher-desktop/issues/2530

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-07-13 01:15 UTC, mook-as requested changes
Lint errors (I haven't actually tried this yet)

2022-07-13 01:15 UTC, mook-as commented on test/e2e/dnslookup_test.go
> +	"golang.org/x/sys/windows"
The imports here look wong — only the `github.com/rancher-sandbox/` imports should be in a separate section.

2022-07-13 22:01 UTC, Nino-K commented
Depends on https://github.com/lima-vm/lima/pull/958

2022-07-14 19:59 UTC, jandubois reviewed
There are at least 2 unrelated changes mixed into the commit:

* adding `cmd.SilenceUsage = true` settings
* appending a final `.` to static hostname definitions

They should really be in a separate commit, even if they are piggy-backing on this PR (which I think is fine, given how trivial the changes are).

Otherwise it looks fine to me, but I haven't actually tested it. Leaving final verdict to @mook-as

2022-07-14 22:16 UTC, mook-as requested changes
Code generally looks fine; I'm having issues with E2E tests, though. Will dig more.

2022-07-14 22:16 UTC, mook-as commented on cmd/peer_linux.go
> -	"golang.org/x/sync/errgroup"
The grouping here is odd.
```suggestion
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"golang.org/x/sync/errgroup"

	"github.com/rancher-sandbox/rancher-desktop-host-resolver/pkg/vmsock"
```

2022-07-14 22:16 UTC, mook-as commented on cmd/peer_linux.go
> +
Not sure why we want the extra new line?

2022-07-16 00:26 UTC, Nino-K commented
> * appending a final `.` to static hostname definitions

I removed the cobra changes out of this PR, however, adding `.` is a fix for failing tests.

2022-07-18 21:05 UTC, mook-as approved these changes
The changes look fine, but E2E tests hate me :(
Approving anyway, since it seems to work for Nino.

2022-07-19 20:35 UTC, merged